[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "c2e"
version = "0.0.0"
description = "C2E: Console Command Engine"
readme = "README.md"
requires-python = ">=3.14"
license = { text = "GPL-3.0" }

authors = [
    { name = "iFamished" }
]

keywords = [
    "command",
    "console",
    "cli",
    "cli-tool",
    "utility",
    "hungerlib",
    "hungernet"
]

dependencies = [
    "hungerlib",
    "mapres",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Systems Administration",
]

[project.urls]
Homepage = "https://github.com/iFamishedX/C2E"
Documentation = "https://github.com/iFamishedX/C2E"
Source = "https://github.com/iFamishedX/C2E"
Issues = "https://github.com/iFamishedX/C2E/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
serverwatcher = ["defaultconfigs/*.yaml"]